-- Realtime Broker Simulation v2
-- Run this file in Supabase SQL Editor. It is safe to run more than once.

create table if not exists public.stocks (
  symbol text primary key,
  name text not null,
  exchange text not null default 'NASDAQ',
  price numeric(12,2) not null check (price >= 0),
  open numeric(12,2) not null check (open >= 0),
  high numeric(12,2) not null check (high >= 0),
  low numeric(12,2) not null check (low >= 0),
  change numeric(8,2) not null default 0,
  volatility numeric(6,3) not null default 0.550 check (volatility >= 0 and volatility <= 20),
  updated_at timestamptz not null default now()
);

alter table public.stocks add column if not exists volatility numeric(6,3) not null default 0.550;
alter table public.stocks add column if not exists manual_override_until timestamptz;
alter table public.stocks replica identity full;

create table if not exists public.stock_price_history (
  id bigint generated by default as identity primary key,
  symbol text not null references public.stocks(symbol) on delete cascade,
  price numeric(12,2) not null check (price >= 0),
  recorded_at timestamptz not null default now(),
  granularity text not null default 'tick' check (granularity in ('tick', 'day')),
  sample_date date not null default current_date
);

create index if not exists stock_price_history_symbol_time_idx
  on public.stock_price_history(symbol, recorded_at desc);
create index if not exists stock_price_history_symbol_granularity_time_idx
  on public.stock_price_history(symbol, granularity, recorded_at desc);

create table if not exists public.demo_accounts (
  id text primary key,
  cash numeric(14,2) not null check (cash >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.demo_holdings (
  account_id text not null references public.demo_accounts(id) on delete cascade,
  symbol text not null references public.stocks(symbol) on delete cascade,
  quantity numeric(14,4) not null default 0 check (quantity >= 0),
  average_cost numeric(12,2) not null default 0 check (average_cost >= 0),
  updated_at timestamptz not null default now(),
  primary key (account_id, symbol)
);

create table if not exists public.demo_orders (
  id uuid primary key default gen_random_uuid(),
  account_id text not null references public.demo_accounts(id) on delete cascade,
  symbol text not null references public.stocks(symbol),
  side text not null check (side in ('buy', 'sell')),
  quantity numeric(14,4) not null check (quantity > 0),
  price numeric(12,2) not null check (price >= 0),
  total numeric(14,2) not null check (total >= 0),
  created_at timestamptz not null default now()
);

create index if not exists demo_orders_account_time_idx
  on public.demo_orders(account_id, created_at desc);

insert into public.stocks (symbol, name, exchange, price, open, high, low, change, volatility)
values
  ('AAPL', 'Apple Inc.', 'NASDAQ', 227.64, 224.88, 229.12, 223.41, 1.23, 0.550),
  ('TSLA', 'Tesla, Inc.', 'NASDAQ', 342.11, 347.01, 349.70, 337.88, -1.42, 0.950),
  ('MSFT', 'Microsoft Corp.', 'NASDAQ', 415.56, 411.22, 418.04, 410.68, 0.84, 0.420),
  ('GOOGL', 'Alphabet Inc.', 'NASDAQ', 176.89, 175.41, 178.34, 174.80, 0.67, 0.500)
on conflict (symbol) do update set volatility = excluded.volatility;

insert into public.demo_accounts (id, cash)
values ('demo-user', 12400.00)
on conflict (id) do nothing;

insert into public.demo_holdings (account_id, symbol, quantity, average_cost)
values
  ('demo-user', 'AAPL', 10, 198.00),
  ('demo-user', 'TSLA', 5, 301.00),
  ('demo-user', 'MSFT', 5, 376.00),
  ('demo-user', 'GOOGL', 10, 152.00)
on conflict (account_id, symbol) do nothing;

-- Seed one year of daily simulated history for each symbol. Existing dates are skipped.
insert into public.stock_price_history (symbol, price, recorded_at, granularity, sample_date)
select
  s.symbol,
  greatest(0.01, round((s.price * (1 + sin(g.day_offset * 0.37 + length(s.symbol)) * 0.08 + (random() - 0.5) * 0.03))::numeric, 2)),
  (current_date - g.day_offset)::timestamptz + interval '12 hours',
  'day',
  current_date - g.day_offset
from public.stocks s
cross join generate_series(0, 364) as g(day_offset)
where not exists (
  select 1 from public.stock_price_history h
  where h.symbol = s.symbol
    and h.granularity = 'day'
    and h.sample_date = current_date - g.day_offset
);

alter table public.stocks enable row level security;
alter table public.stock_price_history enable row level security;
alter table public.demo_accounts enable row level security;
alter table public.demo_holdings enable row level security;
alter table public.demo_orders enable row level security;

drop policy if exists "Public can read stocks" on public.stocks;
create policy "Public can read stocks" on public.stocks for select to anon, authenticated using (true);
drop policy if exists "Public can read price history" on public.stock_price_history;
create policy "Public can read price history" on public.stock_price_history for select to anon, authenticated using (true);
drop policy if exists "Public can read demo account" on public.demo_accounts;
create policy "Public can read demo account" on public.demo_accounts for select to anon, authenticated using (id = 'demo-user');
drop policy if exists "Public can read demo holdings" on public.demo_holdings;
create policy "Public can read demo holdings" on public.demo_holdings for select to anon, authenticated using (account_id = 'demo-user');
drop policy if exists "Public can read demo orders" on public.demo_orders;
create policy "Public can read demo orders" on public.demo_orders for select to anon, authenticated using (account_id = 'demo-user');

do $$
begin
  if not exists (select 1 from pg_publication_rel pr join pg_class c on c.oid = pr.prrelid join pg_namespace n on n.oid = c.relnamespace join pg_publication p on p.oid = pr.prpubid where p.pubname = 'supabase_realtime' and n.nspname = 'public' and c.relname = 'stocks') then
    alter publication supabase_realtime add table public.stocks;
  end if;
  if not exists (select 1 from pg_publication_rel pr join pg_class c on c.oid = pr.prrelid join pg_namespace n on n.oid = c.relnamespace join pg_publication p on p.oid = pr.prpubid where p.pubname = 'supabase_realtime' and n.nspname = 'public' and c.relname = 'demo_accounts') then
    alter publication supabase_realtime add table public.demo_accounts;
  end if;
  if not exists (select 1 from pg_publication_rel pr join pg_class c on c.oid = pr.prrelid join pg_namespace n on n.oid = c.relnamespace join pg_publication p on p.oid = pr.prpubid where p.pubname = 'supabase_realtime' and n.nspname = 'public' and c.relname = 'demo_holdings') then
    alter publication supabase_realtime add table public.demo_holdings;
  end if;
  if not exists (select 1 from pg_publication_rel pr join pg_class c on c.oid = pr.prrelid join pg_namespace n on n.oid = c.relnamespace join pg_publication p on p.oid = pr.prpubid where p.pubname = 'supabase_realtime' and n.nspname = 'public' and c.relname = 'demo_orders') then
    alter publication supabase_realtime add table public.demo_orders;
  end if;
end
$$;

create or replace function public.place_demo_order(p_symbol text, p_side text, p_quantity numeric)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_account demo_accounts%rowtype;
  v_holding demo_holdings%rowtype;
  v_stock stocks%rowtype;
  v_total numeric(14,2);
  v_new_average numeric(12,2);
  v_order_id uuid;
begin
  if p_side not in ('buy', 'sell') then raise exception 'Side must be buy or sell'; end if;
  if p_quantity is null or p_quantity <= 0 then raise exception 'Quantity must be greater than zero'; end if;

  select * into v_stock from stocks where symbol = upper(p_symbol) for update;
  if not found then raise exception 'Stock % was not found', p_symbol; end if;
  select * into v_account from demo_accounts where id = 'demo-user' for update;
  select * into v_holding from demo_holdings where account_id = 'demo-user' and symbol = v_stock.symbol for update;
  v_total := round(v_stock.price * p_quantity, 2);

  if p_side = 'buy' then
    if v_account.cash < v_total then raise exception 'Insufficient cash'; end if;
    v_new_average := round(((coalesce(v_holding.quantity, 0) * coalesce(v_holding.average_cost, 0)) + v_total) / (coalesce(v_holding.quantity, 0) + p_quantity), 2);
    update demo_accounts set cash = cash - v_total, updated_at = now() where id = 'demo-user';
    insert into demo_holdings(account_id, symbol, quantity, average_cost) values ('demo-user', v_stock.symbol, p_quantity, v_new_average)
    on conflict (account_id, symbol) do update set quantity = demo_holdings.quantity + excluded.quantity, average_cost = excluded.average_cost, updated_at = now();
  else
    if coalesce(v_holding.quantity, 0) < p_quantity then raise exception 'Insufficient shares'; end if;
    update demo_accounts set cash = cash + v_total, updated_at = now() where id = 'demo-user';
    update demo_holdings set quantity = quantity - p_quantity, updated_at = now() where account_id = 'demo-user' and symbol = v_stock.symbol;
  end if;

  insert into demo_orders(account_id, symbol, side, quantity, price, total) values ('demo-user', v_stock.symbol, p_side, p_quantity, v_stock.price, v_total) returning id into v_order_id;
  return json_build_object('order_id', v_order_id, 'symbol', v_stock.symbol, 'side', p_side, 'quantity', p_quantity, 'price', v_stock.price, 'total', v_total);
end;
$$;
